import { els, state, bindEditorApi } from "../../app/editorRuntime.js";
import { ASSET_TYPES, NODE_COMPONENT_TYPES } from "../../app/editorDeps.js";
import {
  ANCHOR_OFFSET_LABELS,
  ANCHOR_PICKER_MATRIX,
  ANCHOR_PRESETS,
  EDITABLE_NODE_COMPONENTS,
  HORIZONTAL_ANCHOR_KEYS,
  NODE_COMPONENT_LABELS,
  VERTICAL_ANCHOR_KEYS
} from "../../app/editorConfig.js";

const api = bindEditorApi([
  "clamp",
  "componentKey",
  "createAnchorsFromFrame",
  "createAssetThumbnail",
  "createNodeComponent",
  "cssColorIsSupported",
  "getActivePage",
  "getAssetById",
  "getComponentById",
  "getComponentDisplayName",
  "getComponentReferenceId",
  "getDraggedAssetId",
  "getNodeAnchorFrame",
  "getNodeAnchorPresetId",
  "getNodeAnchors",
  "getNodeComponentProps",
  "getNodeComponents",
  "getNodeLocalFrame",
  "getNodeResolvedLocalFrame",
  "getSelectedNode",
  "getTextureAssets",
  "getTextureNineSliceDefault",
  "getTextureRenderType",
  "hasExplicitNodeComponents",
  "hasNodeComponent",
  "isComponentInstanceNode",
  "isEditingComponentPrimaryNode",
  "isMissingComponentInstanceNode",
  "isNodeActive",
  "isNodeLayoutManagedByParent",
  "isTextureDropAsset",
  "normalizeColorToHex",
  "openAtlasEditor",
  "parseComponentKey",
  "finishAssetDrag",
  "registerFontAsset",
  "renameComponentDefinition",
  "runCommand",
  "selectAssetInBrowser"
]);

export {
  ANCHOR_OFFSET_LABELS,
  ANCHOR_PICKER_MATRIX,
  ANCHOR_PRESETS,
  ASSET_TYPES,
  EDITABLE_NODE_COMPONENTS,
  els,
  HORIZONTAL_ANCHOR_KEYS,
  NODE_COMPONENT_LABELS,
  NODE_COMPONENT_TYPES,
  state,
  VERTICAL_ANCHOR_KEYS
};

export const {
  clamp,
  componentKey,
  createAnchorsFromFrame,
  createAssetThumbnail,
  createNodeComponent,
  cssColorIsSupported,
  getActivePage,
  getAssetById,
  getComponentById,
  getComponentDisplayName,
  getComponentReferenceId,
  getDraggedAssetId,
  getNodeAnchorFrame,
  getNodeAnchorPresetId,
  getNodeAnchors,
  getNodeComponentProps,
  getNodeComponents,
  getNodeLocalFrame,
  getNodeResolvedLocalFrame,
  getSelectedNode,
  getTextureAssets,
  getTextureNineSliceDefault,
  getTextureRenderType,
  hasExplicitNodeComponents,
  hasNodeComponent,
  isComponentInstanceNode,
  isEditingComponentPrimaryNode,
  isMissingComponentInstanceNode,
  isNodeActive,
  isNodeLayoutManagedByParent,
  isTextureDropAsset,
  normalizeColorToHex,
  openAtlasEditor,
  parseComponentKey,
  finishAssetDrag,
  registerFontAsset,
  renameComponentDefinition,
  runCommand,
  selectAssetInBrowser
} = api;
